# Generated by O3DE install

set_property(TARGET PrefabBuilder.Tests
    APPEND_STRING PROPERTY IMPORTED_LOCATION
        $<$<CONFIG:profile>:${LY_ROOT_FOLDER}/bin/Windows/profile/Default/./PrefabBuilder.Tests.dll>
)
set_property(TARGET PrefabBuilder.Tests
    PROPERTY IMPORTED_LOCATION_PROFILE
        ${LY_ROOT_FOLDER}/bin/Windows/profile/Default/./PrefabBuilder.Tests.dll
)
